theme: jekyll-theme-cayman
include: [".well-known"]

repository: cyborgway-org/cyborgway-org
baseurl: ""
url: "https://aleksnlp.com"

# Plugins
plugins:
  - jekyll-multiple-languages-plugin

# jekyll-multiple-languages-plugin settings:
languages: ["en", "ru", "eo"]

exclude_from_localizations: ["assets", "_sass", "_layouts", "_includes"]
